# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:ios)

platform :ios do
  desc "This lints the project for warning fixes."
  
  lane :lint do
  	swiftlint(
  		mode: :lint,
  		path: "../AR2DSkeleton_Starter",
  		output_file: "swiftlint.result.json",
      config_file: ".swiftlint-ci.yml",
      raise_if_swiftlint_error: true,
      ignore_exit_status: true
    )
  end

end
